### ISSUE TITLE
Explore ways in which to pass prolog clauses into Make syntax

### ISSUE THREAD

**Issue by cmungall** [cmungall/biomake#14]
Currently if you want to use LP extensions then you need to use prolog/Makeprog syntax for the entire Makefile.

There are a variety of ways to smuggle in prolog syntax to the Makefile, but these have varying degrees of elegance.

The most straightforward is to embed the prolog in comments, e.g.

```
# PROLOG: mammals <-- Deps, {findall( t([X,'.',Y,'.alignment']),  mammal_pair(X,Y),  Deps )}.
```

This should be straightforward to implement.

But this is a little unsatisfying, as it obscures the new target.

A more makefile-esque way might be:

```
MYDEPS := $prolog( findall( t([X,'.',Y,'.alignment']),  mammal_pair(X,Y),  % ) )

...

mammals: $(MYDEPS)
```

The challenge here is that prolog doesn't return values, it unifies, so we need a way to state that the 3rd argument of this `findall/3` clause should be bound to the stated variable. We could just use a symbol like `%` as I have above or some other convention.

perhaps this is clearer if the pattern is specified in our `$prolog(...)` pseudo-make function:

```
MYDEPS := $prolog( %, findall( t([X,'.',Y,'.alignment']),  mammal_pair(X,Y),  % ) )
```

**Comment by ihh** [comment]
+1
How about `$(bagof Template,Goal)`
which returns the `List` from the Prolog `bagof(Template,Goal,List)`

obviously that only works for lists, but since Make just converts lists to strings anyway (using whitespace as a separator), maybe it's OK?

**Comment by ihh** [comment]
The other thing that would be good is a way to attach Prolog goals to Makefile rules

e.g.

```
$A.target: $A.dep {is_fasta_file(A)}
    do_something $< >$@
```

obviously we already have this in the Prolog syntax ... again, shouldn't be too hard to implement this
